# Generated by Django 6.0.3 on 2026-05-14 20:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('flagged', 'Flagged')], default='pending', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('answered_questions', models.PositiveIntegerField(default=0)),
                ('overall_interview_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cheat_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cheat_flags', models.JSONField(blank=True, default=list)),
                ('session_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('ethical', 'Ethical'), ('scam_detection', 'Scam Detection'), ('security_reasoning', 'Security Reasoning'), ('moderation_sim', 'Moderation Simulation')], max_length=20)),
                ('difficulty', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('question_text', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('expected_topics', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_followup', models.BooleanField(default=False)),
                ('generated_by', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='manager_hiring.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='manager_hiring.interviewsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completeness_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('accuracy_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ai_generated_probability', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('typing_speed_wpm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time_to_answer_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('stylometric_flags', models.JSONField(blank=True, default=list)),
                ('perplexity_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('semantic_consistency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evaluation_metadata', models.JSONField(blank=True, default=dict)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='manager_hiring.interviewquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('resume_parsing', 'Resume Parsing'), ('qualification_review', 'Qualification Review'), ('interview_scheduled', 'Interview Scheduled'), ('interview_in_progress', 'Interview In Progress'), ('interview_completed', 'Interview Completed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='submitted', max_length=25)),
                ('resume_file_url', models.URLField(blank=True)),
                ('resume_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], default='pdf', max_length=10)),
                ('resume_text_extracted', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('extracted_education', models.JSONField(blank=True, default=list)),
                ('extracted_experience', models.JSONField(blank=True, default=list)),
                ('extracted_certifications', models.JSONField(blank=True, default=list)),
                ('qualification_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('candidate_vector', models.JSONField(blank=True, default=list)),
                ('admin_notes', models.TextField(blank=True)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='manager_hiring.managerapplication'),
        ),
        migrations.AddIndex(
            model_name='managerapplication',
            index=models.Index(fields=['status', 'created_at'], name='manager_hir_status_d80943_idx'),
        ),
        migrations.AddIndex(
            model_name='managerapplication',
            index=models.Index(fields=['-overall_score'], name='manager_hir_overall_9e38b4_idx'),
        ),
    ]
