# Generated by Django 6.0.3 on 2026-04-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_is_suspended_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_key",
            field=models.TextField(blank=True, default=""),
        ),
    ]
