# Generated by Django 6.0.3 on 2026-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_email_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True, default="", help_text="Profile picture URL"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, default="", help_text="Short seller bio shown on profile"
            ),
        ),
    ]
