# Generated by Django 6.0.3 on 2026-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_add_bio_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="suspended_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="suspension_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
