# Generated by Django 6.0.3 on 2026-04-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_suspended_until_user_suspension_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="termination_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
