# Generated by Django 6.0.3 on 2026-04-04 03:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0002_add_listing_demo"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostSaleReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        help_text="Whether the method worked for the buyer"
                    ),
                ),
                (
                    "earnings",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual earnings achieved",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "roi_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual ROI achieved",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "time_to_results",
                    models.DurationField(
                        blank=True, help_text="Time taken to achieve results", null=True
                    ),
                ),
                (
                    "feedback",
                    models.TextField(help_text="Detailed feedback on the method"),
                ),
                (
                    "satisfaction_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Satisfaction score (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "difficulties_faced",
                    models.TextField(blank=True, help_text="Difficulties encountered"),
                ),
                (
                    "support_quality",
                    models.IntegerField(
                        blank=True,
                        help_text="Support quality rating (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("would_purchase_again", models.BooleanField(blank=True, null=True)),
                ("would_recommend", models.BooleanField(blank=True, null=True)),
                ("additional_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_sale_report",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingDemo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "demo_category",
                    models.CharField(
                        choices=[
                            ("fullz", "Fullz / Data Dumps"),
                            ("proxies", "Proxies & Anonymity"),
                            ("bypass", "Account Bypass"),
                            ("bank", "Bank / Payment Withdrawals"),
                            ("freelancing", "Freelancing Sites"),
                            ("general", "General"),
                        ],
                        default="general",
                        help_text="The type of information being demonstrated",
                        max_length=20,
                    ),
                ),
                (
                    "demo_text",
                    models.TextField(
                        blank=True,
                        help_text="Short public excerpt / redacted teaser (max 800 chars)",
                        max_length=800,
                    ),
                ),
                (
                    "demo_files",
                    models.JSONField(
                        default=list,
                        help_text="Redacted proof files (screenshots, logs, receipts) — stored as [{url, type, caption, file_hash}]",
                    ),
                ),
                (
                    "guidance_acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="Seller confirmed they understand redaction requirements",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Admin has reviewed and approved the demo material",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason demo was rejected (if applicable)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who approved this demo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_demos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["listing", "is_approved"],
                        name="verificatio_listing_5aa474_idx",
                    ),
                    models.Index(
                        fields=["demo_category"], name="verificatio_demo_ca_7183a4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Proof",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot"),
                            ("video", "Video"),
                            ("log", "Log File"),
                            ("receipt", "Receipt"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(help_text="S3 URL to the proof file")),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the file", max_length=64
                    ),
                ),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Timestamps, notes, and other metadata"
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
                ("validation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["listing", "type"],
                        name="verificatio_listing_954eb0_idx",
                    ),
                    models.Index(
                        fields=["file_hash"], name="verificatio_file_ha_6d1e6f_idx"
                    ),
                    models.Index(
                        fields=["is_validated"], name="verificatio_is_vali_712a21_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReproducibilityTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        help_text="Whether the method was successfully reproduced"
                    ),
                ),
                (
                    "earnings_reported",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Earnings achieved from reproduction test",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "roi_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Return on investment percentage",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "time_to_results",
                    models.DurationField(
                        blank=True, help_text="Time taken to see results", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(help_text="Detailed test notes and observations"),
                ),
                (
                    "challenges_faced",
                    models.TextField(
                        blank=True, help_text="Challenges during reproduction"
                    ),
                ),
                (
                    "environment_details",
                    models.JSONField(
                        default=dict, help_text="Test environment specifications"
                    ),
                ),
                (
                    "supporting_evidence",
                    models.JSONField(
                        default=list, help_text="Links to screenshots, logs, etc."
                    ),
                ),
                (
                    "would_recommend",
                    models.BooleanField(
                        blank=True, help_text="Would recommend to others", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reproducibility_tests",
                        to="listings.listing",
                    ),
                ),
                (
                    "tester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["listing", "success"],
                        name="verificatio_listing_a3237d_idx",
                    ),
                    models.Index(
                        fields=["tester", "created_at"],
                        name="verificatio_tester__bda193_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("partial", "Partial"),
                            ("needs_info", "Needs More Information"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence in verdict (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("notes", models.TextField(help_text="Detailed verification notes")),
                (
                    "evidence_reviewed",
                    models.TextField(help_text="List of evidence and proofs reviewed"),
                ),
                (
                    "testing_methodology",
                    models.TextField(
                        blank=True, help_text="How the verification was conducted"
                    ),
                ),
                (
                    "identified_risks",
                    models.JSONField(
                        default=list, help_text="List of identified risks"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="Recommendations for improvement"
                    ),
                ),
                (
                    "time_spent_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Time spent on verification"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="listings.listing",
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["listing", "verdict"],
                        name="verificatio_listing_cba398_idx",
                    ),
                    models.Index(
                        fields=["verifier", "created_at"],
                        name="verificatio_verifie_7c2da9_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="verificatio_created_f7326b_idx"
                    ),
                ],
                "unique_together": {("listing", "verifier")},
            },
        ),
        migrations.CreateModel(
            name="VerificationConsensus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "final_verdict",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("partial", "Partial"),
                            ("needs_info", "Needs More Information"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("total_verifications", models.PositiveIntegerField(default=0)),
                ("valid_votes", models.PositiveIntegerField(default=0)),
                ("invalid_votes", models.PositiveIntegerField(default=0)),
                ("partial_votes", models.PositiveIntegerField(default=0)),
                ("needs_info_votes", models.PositiveIntegerField(default=0)),
                ("consensus_threshold_met", models.BooleanField(default=False)),
                (
                    "final_notes",
                    models.TextField(
                        help_text="Summary of all verifications and consensus reasoning"
                    ),
                ),
                (
                    "risk_assessment",
                    models.JSONField(default=dict, help_text="Final risk assessment"),
                ),
                (
                    "recommendations",
                    models.JSONField(default=list, help_text="Final recommendations"),
                ),
                ("determined_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "determined_by",
                    models.ForeignKey(
                        help_text="Admin who determined the final consensus",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_consensus",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["listing", "final_verdict"],
                        name="verificatio_listing_659c12_idx",
                    ),
                    models.Index(
                        fields=["determined_at"], name="verificatio_determi_bf7482_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerificationQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "auto_assigned",
                    models.BooleanField(
                        default=False, help_text="Whether auto-assignment was used"
                    ),
                ),
                (
                    "estimated_complexity",
                    models.IntegerField(
                        default=3,
                        help_text="Estimated complexity (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "special_instructions",
                    models.TextField(
                        blank=True, help_text="Special instructions for verifiers"
                    ),
                ),
                (
                    "escalation_reason",
                    models.TextField(blank=True, help_text="Reason for escalation"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_verifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_queue",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "priority", "created_at"],
                        name="verificatio_status_b59c5f_idx",
                    ),
                    models.Index(
                        fields=["assigned_verifier", "status"],
                        name="verificatio_assigne_d29a69_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerificationScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "base_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "reproducibility_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "post_sale_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "seniority_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "penalty_factors",
                    models.JSONField(
                        default=list,
                        help_text="List of penalty factors and their values",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "success_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Success rate based on post-sale reports",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_score_record",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-final_score"], name="verificatio_final_s_8e5fca_idx"
                    ),
                    models.Index(
                        fields=["success_rate"], name="verificatio_success_8579e2_idx"
                    ),
                ],
            },
        ),
    ]
