# Generated by Django 6.0.3 on 2026-05-14 20:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_preview_media'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash_sha256', models.CharField(db_index=True, max_length=64)),
                ('metadata_hash', models.CharField(blank=True, max_length=64)),
                ('embedding_vector', models.JSONField(blank=True, default=list, help_text='Semantic embedding for similarity search')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('fingerprint_version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipLineage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acquisition_type', models.CharField(choices=[('original', 'Original Upload'), ('purchase', 'Purchase'), ('transfer', 'Transfer')], default='original', max_length=20)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_products', to=settings.AUTH_USER_MODEL)),
                ('parent_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='fraud_detection.ownershiplineage')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
                ('fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_entries', to='fraud_detection.productfingerprint')),
            ],
            options={
                'ordering': ['acquired_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateDetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('hash_match', models.BooleanField(default=False)),
                ('semantic_match', models.BooleanField(default=False)),
                ('metadata_match', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('no_match', 'No Match'), ('possible_duplicate', 'Possible Duplicate'), ('confirmed_duplicate', 'Confirmed Duplicate'), ('false_positive', 'False Positive')], default='pending', max_length=25)),
                ('review_notes', models.TextField(blank=True)),
                ('scan_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matched_fingerprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_by', to='fraud_detection.productfingerprint')),
                ('source_fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_scans', to='fraud_detection.productfingerprint')),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='ReuploadAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fraud_detection.duplicatedetectionresult')),
                ('flagged_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reupload_alerts', to='listings.listing')),
                ('original_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reupload_claims', to='listings.listing')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('scam', 'Scam'), ('reupload', 'Reupload'), ('fake_proof', 'Fake Proof'), ('identity', 'Identity Fraud'), ('other', 'Other')], max_length=15)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='submitted', max_length=15)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_reports', to='listings.listing')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'report_type'], name='fraud_detec_status_000c6c_idx'), models.Index(fields=['reported_user'], name='fraud_detec_reporte_c1857f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productfingerprint',
            index=models.Index(fields=['content_hash_sha256'], name='fraud_detec_content_417ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='productfingerprint',
            index=models.Index(fields=['metadata_hash'], name='fraud_detec_metadat_f9fa85_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiplineage',
            index=models.Index(fields=['fingerprint', 'owner'], name='fraud_detec_fingerp_ae1484_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicatedetectionresult',
            index=models.Index(fields=['status', 'similarity_score'], name='fraud_detec_status_f7da22_idx'),
        ),
        migrations.AddIndex(
            model_name='reuploadalert',
            index=models.Index(fields=['status', 'severity'], name='fraud_detec_status_a8f335_idx'),
        ),
    ]
