# Generated by Django 6.0.3 on 2026-05-14 20:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerTrustProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Composite trust score 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('successful_transactions', models.PositiveIntegerField(default=0)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('scam_reports_received', models.PositiveIntegerField(default=0)),
                ('verification_success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('buyer_satisfaction_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('escrow_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('product_authenticity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('reupload_violations', models.PositiveIntegerField(default=0)),
                ('dispute_frequency', models.DecimalField(decimal_places=2, default=0.0, help_text='Disputes per 100 transactions', max_digits=5)),
                ('communication_quality', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('tier', models.CharField(choices=[('new', 'New Seller'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='new', max_length=10)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReputationBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('verified_seller', 'Verified Seller'), ('top_rated', 'Top Rated'), ('fast_delivery', 'Fast Delivery'), ('dispute_free', 'Dispute Free'), ('escrow_reliable', 'Escrow Reliable'), ('community_trusted', 'Community Trusted'), ('high_volume', 'High Volume'), ('long_standing', 'Long Standing')], max_length=30)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trust_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='ratings.sellertrustprofile')),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trust_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tier', models.CharField(max_length=10)),
                ('snapshot_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trust_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='ratings.sellertrustprofile')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunityTrustVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('trusted', 'Trusted'), ('suspicious', 'Suspicious'), ('neutral', 'Neutral')], max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_votes_received', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'vote'], name='ratings_com_seller__0f7209_idx')],
                'unique_together': {('voter', 'seller')},
            },
        ),
        migrations.AddIndex(
            model_name='sellertrustprofile',
            index=models.Index(fields=['-trust_score'], name='ratings_sel_trust_s_ef9fee_idx'),
        ),
        migrations.AddIndex(
            model_name='sellertrustprofile',
            index=models.Index(fields=['tier'], name='ratings_sel_tier_3b3c23_idx'),
        ),
        migrations.AddIndex(
            model_name='sellertrustprofile',
            index=models.Index(fields=['seller'], name='ratings_sel_seller__a42e1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reputationbadge',
            unique_together={('trust_profile', 'badge_type')},
        ),
        migrations.AddIndex(
            model_name='ratingsnapshot',
            index=models.Index(fields=['trust_profile', 'snapshot_date'], name='ratings_rat_trust_p_a7610c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingsnapshot',
            unique_together={('trust_profile', 'snapshot_date')},
        ),
    ]
