# Generated by Django 6.0.3 on 2026-05-14 20:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_preview_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentWeightConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('qualification_weight', models.DecimalField(decimal_places=2, default=0.15, max_digits=4)),
                ('experience_weight', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
                ('verification_accuracy_weight', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('scam_detection_weight', models.DecimalField(decimal_places=2, default=0.15, max_digits=4)),
                ('seller_rating_weight', models.DecimalField(decimal_places=2, default=0.05, max_digits=4)),
                ('buyer_rating_weight', models.DecimalField(decimal_places=2, default=0.05, max_digits=4)),
                ('activity_weight', models.DecimalField(decimal_places=2, default=0.05, max_digits=4)),
                ('consistency_weight', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
                ('speed_weight', models.DecimalField(decimal_places=2, default=0.05, max_digits=4)),
                ('trust_weight', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
                ('randomization_factor', models.DecimalField(decimal_places=2, default=0.15, help_text='Amount of randomization injected for fairness', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualification_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verification_accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scam_detection_accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('seller_rating_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('buyer_rating_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('platform_activity_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('task_completion_consistency', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_response_speed_minutes', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('trust_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('composite_rank_score', models.DecimalField(decimal_places=4, default=0.0, help_text='Weighted composite used for assignment priority', max_digits=7)),
                ('total_tasks_completed', models.PositiveIntegerField(default=0)),
                ('total_tasks_assigned', models.PositiveIntegerField(default=0)),
                ('active_assignments', models.PositiveIntegerField(default=0)),
                ('max_concurrent_assignments', models.PositiveIntegerField(default=5)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('last_assignment_at', models.DateTimeField(blank=True, null=True)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-composite_rank_score'], name='task_engine_composi_072f1f_idx'), models.Index(fields=['is_available', '-composite_rank_score'], name='task_engine_is_avai_76a11d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskConsensus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('clean_count', models.PositiveIntegerField(default=0)),
                ('suspicious_count', models.PositiveIntegerField(default=0)),
                ('fraud_count', models.PositiveIntegerField(default=0)),
                ('escalated_count', models.PositiveIntegerField(default=0)),
                ('aggregate_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('consensus_status', models.CharField(choices=[('open', 'Open'), ('consensus_reached', 'Consensus Reached'), ('split_verdict', 'Split Verdict'), ('escalated', 'Escalated')], default='open', max_length=25)),
                ('final_decision', models.CharField(blank=True, max_length=20)),
                ('determined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_consensus', to='listings.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['consensus_status'], name='task_engine_consens_a916c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('total_chunks', models.PositiveIntegerField(default=1)),
                ('chunk_data_ref', models.CharField(blank=True, help_text='Reference to encrypted chunk (no plaintext)', max_length=255)),
                ('randomized_batch_label', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('escalated', 'Escalated'), ('reassigned', 'Reassigned'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('assignment_weight', models.DecimalField(decimal_places=4, default=1.0, help_text='Weight used during assignment', max_digits=7)),
                ('decision', models.CharField(blank=True, choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('fraud_signal', 'Fraud Signal'), ('escalate', 'Escalate')], max_length=20)),
                ('review_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('review_notes', models.TextField(blank=True)),
                ('review_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tasks', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='task_engine_status_425793_idx'), models.Index(fields=['assigned_manager', 'status'], name='task_engine_assigne_28c7db_idx'), models.Index(fields=['listing', 'chunk_index'], name='task_engine_listing_28a424_idx')],
            },
        ),
    ]
