# Generated by Django 6.0.3 on 2026-05-14 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_locked', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_released', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_slashed', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StakeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_sale_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stake_rate', models.DecimalField(decimal_places=2, default=0.4, help_text='Fraction of gross sale locked (default 0.40 = 40%)', max_digits=4)),
                ('locked_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('pending_release', 'Pending Release'), ('released', 'Released'), ('slashed', 'Slashed'), ('disputed', 'Disputed')], default='locked', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scam_review_status', models.CharField(choices=[('not_flagged', 'Not Flagged'), ('queued', 'Queued'), ('cleared', 'Cleared'), ('escalated', 'Escalated')], default='not_flagged', max_length=20)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_release_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('escrow_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stake_entries', to='escrow.escrowaccount')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_stakes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_stakes', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-locked_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(help_text='When the release should execute')),
                ('executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stake_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_schedule', to='escrow.stakeentry')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('stake_created', 'Stake Created'), ('verification_started', 'Verification Started'), ('verification_passed', 'Verification Passed'), ('verification_failed', 'Verification Failed'), ('release_scheduled', 'Release Scheduled'), ('released', 'Released'), ('slashed', 'Slashed'), ('dispute_frozen', 'Dispute Frozen'), ('dispute_resolved', 'Dispute Resolved')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stake_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='escrow.stakeentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['user'], name='escrow_escr_user_id_b441d9_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeentry',
            index=models.Index(fields=['status', 'locked_at'], name='escrow_stak_status_0f60ad_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeentry',
            index=models.Index(fields=['escrow_account', 'status'], name='escrow_stak_escrow__6303bc_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeentry',
            index=models.Index(fields=['verification_status'], name='escrow_stak_verific_00ff53_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseschedule',
            index=models.Index(fields=['scheduled_at', 'executed'], name='escrow_rele_schedul_f9a0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowevent',
            index=models.Index(fields=['stake_entry', 'event_type'], name='escrow_escr_stake_e_77d64e_idx'),
        ),
    ]
