# Generated by Django 6.0.3 on 2026-04-04 03:39

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="estimated_difficulty",
            field=models.IntegerField(
                blank=True,
                help_text="Estimated difficulty (1-10)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="potential_earnings",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated potential earnings",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="required_skills",
            field=models.TextField(blank=True, help_text="Required skills and tools"),
        ),
        migrations.AddField(
            model_name="listing",
            name="requires_reverification",
            field=models.BooleanField(
                default=False, help_text="Whether listing needs re-verification"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("extreme", "Extreme"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="success_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Success rate based on post-sale reports",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="time_investment",
            field=models.DurationField(
                blank=True, help_text="Estimated time investment", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="verification_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When verification expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="verification_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Overall verification score (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("in_review", "In Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("partial", "Partial"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_verification", "Pending Verification"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("partial", "Partially Verified"),
                    ("active", "Active"),
                    ("sold", "Sold"),
                    ("flagged", "Flagged"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["verification_status", "verification_score"],
                name="listings_li_verific_8402f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-verification_score"], name="listings_li_verific_b831bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-success_rate"], name="listings_li_success_65d273_idx"
            ),
        ),
    ]
