# Generated by Django 6.0.3 on 2026-04-04 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_add_listing_demo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingPreviewMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        help_text="MinIO/S3 public or presigned URL", max_length=1024
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveBigIntegerField(default=0, help_text="Bytes"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=127)),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_media",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
